# Generated by Django 3.1.4 on 2021-02-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadres',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('position', models.CharField(max_length=20, verbose_name='职务')),
                ('phone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('QQ', models.CharField(max_length=20, verbose_name='QQ')),
            ],
            options={
                'verbose_name': '班级干部',
                'verbose_name_plural': '班级干部',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('department', models.CharField(choices=[('计算机院', '计算机院'), ('体育学院', '体育学院'), ('音乐学院', '音乐学院')], max_length=20, verbose_name='院系')),
                ('phone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('subject', models.CharField(choices=[('数学', '数学'), ('语文', '语文'), ('英语', '英语')], max_length=20, verbose_name='科目')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='课程名')),
                ('score', models.CharField(max_length=10, verbose_name='学分')),
                ('all_time', models.IntegerField(verbose_name='总学时')),
                ('theoretical_time', models.IntegerField(verbose_name='理论学时')),
                ('practice_time', models.IntegerField(verbose_name='实践学时')),
                ('category', models.CharField(choices=[('专业课、任选课', '专业课、任选课'), ('专业课、必修课', '专业课、必修课'), ('专业课、限选课', '专业课、限选课'), ('公共课、必修课', '公共课、必修课'), ('公共课、任选课', '公共课、任选课')], max_length=20, verbose_name='类别')),
                ('assessment', models.CharField(choices=[('过程考核', '过程考核'), ('闭卷', '闭卷')], max_length=20, verbose_name='考核方式')),
                ('week_time', models.CharField(max_length=20, verbose_name='周次')),
                ('time', models.CharField(max_length=20, verbose_name='上课时间')),
                ('place', models.CharField(max_length=20, verbose_name='上课地点')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='function.teacher', verbose_name='任课教师')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
    ]
