# Generated by Django 3.1.4 on 2021-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='method',
            field=models.CharField(choices=[('理论', '理论'), ('上机', '上机')], default='理论', max_length=20, verbose_name='授课方式'),
        ),
    ]
