# Generated by Django 3.1.4 on 2021-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_curriculum_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='all_time',
            field=models.IntegerField(verbose_name='p总学时'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=20, verbose_name='课程名'),
        ),
    ]
