# Generated by Django 3.1.4 on 2021-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_auto_20210223_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='all_time',
            field=models.IntegerField(verbose_name='总学时'),
        ),
    ]
