# Generated by Django 3.1.4 on 2021-02-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0004_auto_20210223_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='id',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='课程名'),
        ),
    ]
