# Generated by Django 3.1.4 on 2021-02-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_remove_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=20, verbose_name='性别'),
        ),
    ]
