# Generated by Django 3.1.4 on 2021-02-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0007_teacher_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
