# Generated by Django 3.1.4 on 2021-02-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0008_remove_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='teacher',
            field=models.CharField(default=None, max_length=20, verbose_name='任课教师'),
        ),
    ]
