# Generated by Django 3.1.4 on 2021-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0010_auto_20210223_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=None, verbose_name='课程名'),
        ),
    ]
