# Generated by Django 3.1.4 on 2021-02-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0012_delete_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=None, verbose_name='课程名')),
                ('score', models.CharField(max_length=10, verbose_name='学分')),
                ('all_time', models.IntegerField(verbose_name='总学时')),
                ('theoretical_time', models.IntegerField(verbose_name='理论学时')),
                ('practice_time', models.IntegerField(verbose_name='实践学时')),
                ('category', models.CharField(choices=[('专业课、任选课', '专业课、任选课'), ('专业课、必修课', '专业课、必修课'), ('专业课、限选课', '专业课、限选课'), ('公共课、必修课', '公共课、必修课'), ('公共课、任选课', '公共课、任选课')], max_length=20, verbose_name='类别')),
                ('method', models.CharField(choices=[('理论', '理论'), ('上机', '上机')], default='理论', max_length=20, verbose_name='授课方式')),
                ('assessment', models.CharField(choices=[('过程考核', '过程考核'), ('闭卷', '闭卷')], max_length=20, verbose_name='考核方式')),
                ('teacher', models.CharField(default=None, max_length=20, verbose_name='任课教师')),
                ('week_time', models.CharField(max_length=20, verbose_name='周次')),
                ('time', models.CharField(max_length=20, verbose_name='上课时间')),
                ('place', models.CharField(max_length=20, verbose_name='上课地点')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
    ]
