# Generated by Django 3.1.4 on 2021-02-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0013_curriculum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
